### ISSUE TITLE
Does sshd not support sock5 forwarding proxy?

### ISSUE THREAD

**Issue by leild** [apache/mina-sshd#261]
Does sshd not support sock5 forwarding proxy? 

![image](https://user-images.githubusercontent.com/43057576/199208541-813ac18f-0a90-47f5-9220-6fbd861406c3.png)
Can the core code be modified to add a proxy that supports multiple protocols?

**Comment by tomaswolf** [comment]
Client-side the only support is via the `ClientProxyConnector` and `SshClient.setClientProxyConnector()`.

See also [SSHD-1008](https://issues.apache.org/jira/browse/SSHD-1008).

**Comment by leild** [comment]
![image](https://user-images.githubusercontent.com/43057576/200158650-744c121b-7f51-49c4-8dcf-e00b78906864.png)
Can this code be modified to provide an external support interface, more friendly support, reduce TODO？Thanks.

**Comment by tomaswolf** [comment]
The comment refers to making the logging configurable.

If you want to use Netty and create your own pipeline, go ahead an plug in a custom-written `IoServiceFactoryFactory`. The Apache MINA sshd `IoService` is an abstraction that is independent of the actual implementation, and it doesn't have the concept of a pipeline or filter chain.
