### ISSUE TITLE
I wants to use Apache MINA sshd to talk to old SSH servers  what do i do ?

### ISSUE THREAD

**Issue by small-thunder** [apache/mina-sshd#269]
use sshclient connect  server which sshd version is 1.3~1.99  error
Because the server version is low the client has strong version validation
![image](https://user-images.githubusercontent.com/43597696/201071243-fe3989b7-f59a-4fb7-803b-33db1aa23439.png)
![image](https://user-images.githubusercontent.com/43597696/201071263-299947aa-0dd0-4e23-8062-9442ace50b59.png)

How do I use sshclient to connect to this lower version of the server？

Does sshd not support  talk to old SSH servers?

**Comment by small-thunder** [comment]
Because the server version is low the client has strong version verification
![0b9fb0e778db6320f8b2b5eb1870e70](https://user-images.githubusercontent.com/43597696/201070625-44968b26-f1d7-42b6-8718-8094537bc64e.png)
![d7340c3d92fac7c1f8513b5b96d7602](https://user-images.githubusercontent.com/43597696/201070647-0621e676-5573-4539-a76c-1164c8026e88.png)

How can I use sshclient to connect to this lower version of the server ?

**Comment by tomaswolf** [comment]
> Does sshd not support talk to old SSH servers?

No, it doesn't. Apache MINA SSHD implements only SSH-2.0 as specified by the [RFCs](https://github.com/apache/mina-sshd/blob/master/README.md#reference-implementation-documentation).

**Comment by small-thunder** [comment]
Thank you for explanation
