### ISSUE TITLE
Threads like sshd-SshClient[3c0574ec]-nio2-thread-17 Not Released even after .sshSession.close();

### ISSUE THREAD

**Issue by pu2925** [apache/mina-sshd#270]
We 

We are creating a session like 
 ClientSession session = (ClientSession)((ConnectFuture)client.connect(loginUserName, hostName, 22).verify(2L, TimeUnit.SECONDS)).getSession();
...
session.addPublicKeyIdentity(keys.iterator().next());
..
 session.auth().verify(120000L, TimeUnit.MILLISECONDS);

After doing a PUT File operation ( Method like below ) and doing the session close like  sshSession.close();

We see Threads like sshd-SshClient[3c0574ec]-nio2-thread-17 not getting released.  
  

**Put File method**
public static void putFile(ClientSession session, String srcPath, String destPathForPut) throws SSHConnectionException {
    try(SftpClient sftpClient = DefaultSftpClientFactory.INSTANCE.createSftpClient(session); 
        OutputStream o = sftpClient.write(destPathForPut, new SftpClient.OpenMode[] { SftpClient.OpenMode.Create, SftpClient.OpenMode.Write, SftpClient.OpenMode.Truncate }); BufferedOutputStream os = new BufferedOutputStream(o)) {
      File sourceFile = new File(srcPath);
      Files.copy(sourceFile.toPath(), os);
    } catch (IOException e) {
      s_log.log(Level.SEVERE, "Failed to store content via sftp at " + destPathForPut + " on host due to " + e
          .getMessage(), e);
      throw new SSHConnectionException("Failed to store content via sftp at " + destPathForPut + " on host due to " + e
          
          .getMessage(), e);
    } 
  }

**Comment by pu2925** [comment]
Thread Structure 
sshd-SshClient[3c0574ec]-nio2-thread-17
PRIORITY : 5

THREAD ID : 0X00007F362001B800

NATIVE ID : 0X688E

NATIVE ID (DECIMAL) : 26766

STATE : WAITING


stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000000a3c0ec90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by tomaswolf** [comment]
These are I/O threads belonging to a thread pool that should be shut down when the SshClient is closed. These threads are not tied to a session. So the presence of these threads after the session has been closed does not indicate a problem.
