### ISSUE TITLE
connection pool improve performance

### ISSUE THREAD

**Issue by andotorg** [apache/mina-sshd#279]
### Description

How does sshd use the connection pool to reuse connections to improve performance

### Motivation

How does sshd use the connection pool to reuse connections to improve performance

**Comment by tomaswolf** [comment]
Which connection pool? If you want a pool of SSH connections, implement it _on top_ of the library.

**Comment by andotorg** [comment]
Not a connection, I want to reuse connections, and then improve connection performance, ssh connection pool

**Comment by andotorg** [comment]
Similar to database connection pool
