### ISSUE TITLE
may i ask do this framwork support chinese language?

### ISSUE THREAD

**Issue by zhhqcoder** [apache/mina-sshd#280]
### Description

may i ask do this framwork support chinese language?

### Motivation

i can not work out when i tapped chinese characters

**Comment by tomaswolf** [comment]
Which framework? If you mean _this form_ on GitHub for bug tracking: please do not write in Chinese. The people who are most likely to read and answer your issue (the maintainers of the Apache MINA SSHD library) do not understand Chinese and cannot speak, read or write Chinese. Write in English.

If you mean by "framework" the Apache MINA SSHD library itself, then I do not understand the question.
