### ISSUE TITLE
Adding custom filter to filter chain on sftp

### ISSUE THREAD

**Issue by dragonknight88** [apache/mina-sshd#290]
Im trying to find ways to add custom filter to filter chain. But ServerSession/IoSession doesn't provide a simpler way to inject custom filter. 
Im using _SshServer.setUpDefaultServer_ from _org.apache.sshd.server_ which doesn't expose the IoAcceptor to be able to add filter to the chain.

Any recommendations or resources would be greatly appreciated. 

Referring to docs [here](https://mina.apache.org/mina-project/userguide/ch5-filters/ch5-filters.html)

**Comment by tomaswolf** [comment]
The IoConnector/IoAcceptor/IoSession layer is an abstraction over several implementations (NIO2, MINA, Netty). Yes, it does not expose the MINA filter chain, nor the Netty pipeline. If you need access to the MINA filter chain, you're probably best off by creating your own transport back-end based on the existing org.apache.sshd.mina and customizing the filter chain there.
