### ISSUE TITLE
How to: Unable to access session statistics

### ISSUE THREAD

**Issue by dragonknight88** [apache/mina-sshd#291]
I have implemented the _sessionClosed_  of **_org.apache.sshd.common.session.SessionListener_** to access session stats; but  couldn't access to methods specified for variables [here](https://mina.apache.org/mina-project/userguide/ch4-session/ch4.2-session-statistics.html) on session/IoSession. 

As a workaround currently I have overridden read and written methods of _AbstractSftpEventListenerAdapter_ to pull dataLen. 
Is there any other/right way I could access these stats?

**Comment by tomaswolf** [comment]
The IoConnector/IoAcceptor/IoSession layer is an abstraction over several implementations (NIO2, MINA, Netty). Yes, it does not expose the MINA-specific per-session statistics. If you need access to these statistics from MINA, you're probably best off by creating your own transport back-end based on the existing org.apache.sshd.mina and returning a customized MinaSession that does have accessors for the statistics you need.

At a higher level, you can then get the IoSession from the SSH session, downcast to your own class, and call the getters.
