### ISSUE TITLE
Memory Leak in SftpFileSystemProvider 

### ISSUE THREAD

**Issue by sparkchans** [apache/mina-sshd#294]
### Version

master

### Bug description

The newInputStream and newOutputStream methods of SftpFileSystemProvider call the SftpFileSystem#getClient() method without call the close() method:
![image](https://user-images.githubusercontent.com/43289294/208292345-c36f3ebd-2a29-47b8-841a-29ad6a5cc719.png)

### Actual behavior

I have a thread that uploads a file to the server every 10 seconds, as time goes by, the heap memory will get bigger and bigger, and eventually the heap memory will occur out of memory:
![image](https://user-images.githubusercontent.com/43289294/208462429-2ae668de-b295-4f63-895e-d0a6be944d96.png)

When I exported the heap memory, I found that there are a lot of objects of org.apache.sshd.sftp.client.fs.SftpFileSystem$Wrapper
![image](https://user-images.githubusercontent.com/43289294/208296946-ce5be3c5-be88-4a55-ac68-e57ca63618ec.png)

### Expected behavior

When the program is running normally, the heap memory will not overflow

**Comment by luchenguang** [comment]
Meet the same question when using SftpFileSystem, seems to be caused by SftpFileSystem using a ThreadLocal to cache a sftp client but unable to clear it

**Comment by hitYunhongXu** [comment]
hello, how can i get the code without memory leak? it seems that the problem is not fixed in version 2.9.2

**Comment by 2tu** [comment]
@tomaswolf  
I use ThreadPool upload many files.
sftp version：2.9.3-SNAPSHOT
Using the 2.9.3-SNAPSHOT, still unable to release.

![image](https://user-images.githubusercontent.com/14172964/226101500-09c74dca-b1d7-4e0f-9bf5-4a1ac961c8ef.png)

**Comment by 2tu** [comment]
I switched to SftpClient and it's working normally now.

in **_ThreadPool_** use

#### Bad
```java
    public String downloadFile(String path) {
        try (ClientSession session = client.connect(username, host, port).verify(timeout, TimeUnit.SECONDS).getSession()) {
            session.addPasswordIdentity(password);
            session.auth().verify();
            try (SftpFileSystem fs = SftpClientFactory.instance().createSftpFileSystem(session);
                 ByteArrayOutputStream out = new ByteArrayOutputStream()
            ) {
                Path targetPath = fs.getDefaultDir().resolve(path);
                Files.copy(targetPath, out);
                return out.toString("UTF-8");
            }
        } catch (SftpException e) {
            log.error("download file:{} error:{}.", path, e.getMessage());
        } catch (Exception e) {
            log.error("download file:{} error.", path, e);
        }
        return null;
    }
```

#### Good

Version：2.8.0

```java
    public String downloadFile(String path) {
        try (ClientSession session = client.connect(username, host, port).verify(timeout, TimeUnit.SECONDS).getSession()) {
            session.addPasswordIdentity(password);
            session.auth().verify();

            SftpClientFactory factory = SftpClientFactory.instance();

            try (SftpClient sftp = factory.createSftpClient(session);
                 StringWriter writer = new StringWriter();) {
                InputStream inputStream = sftp.read(path);
                IOUtils.copy(inputStream, writer, StandardCharsets.UTF_8);

                String contentStr = writer.toString();

                return contentStr;
            }
        } catch (IOException e) {
            log.error("download file:{} error.", path, e);
        }
        return null;
    }
```

After downloading, moving, and parsing approximately 40142 files, Each file has an approximate size of 4KB.
![image](https://user-images.githubusercontent.com/14172964/226114375-8230f563-4c85-4f60-8e75-ebb295ee404e.png)

**Comment by tomaswolf** [comment]
I cannot reproduce this. Can you show fully working test code using a thread pool (I presume from an ExecutorService) that downloads a number of files and where at the end, when all downloads are done, there are extra ThreadLocals in the pool threads?
