### ISSUE TITLE
SSHD Client failing on private key file with key password

### ISSUE THREAD

**Issue by ascertsimonm** [apache/mina-sshd#297]
### Version

2.9.2

### Bug description

When attempting to run the SSH client with that private key file that is protected with a password the Mina SSH client doesn't make the connection.

The client was run using the command

`java -jar MinaSshClient-2.9.2.jar -i K:\id_rsa myuser@192.168.247.129`

### Actual behavior

The client seems to fail to load the key resource with the following warning

`WARNING: org.apache.sshd.cli.client.SshCl: Failed (FailedLoginException) to load key resource=K:\id_rsa: No password provider for encrypted key in K:\id_rsa`

the connection subsequently fails with a "No more authentication methods available"

### Expected behavior

The client should prompt for a password for the key file or have another command line parameter to specify it.

### Other information

I did a bit of debugging on this and for whatever reason the prompt for the password for the private key file isn't being triggered by the code in the _SshClientCliSupport_,  _setupSessionIdentities_ method.  

Whether or not it's the correct solution what  I did in my own code is I used the setPasswordFinder method on the FileKeyPairProvider with the same code segment as for the client `setFilePasswordProvider` and it seemed to work.

**Comment by tomaswolf** [comment]
If you mean that you added in [SshClientCliSupport, line 508](https://github.com/apache/mina-sshd/blob/78ed6bc9/sshd-cli/src/main/java/org/apache/sshd/cli/client/SshClientCliSupport.java#L508) something like
```
provider.setPasswordFinder(client.getFilePasswordProvider());
```
I agree that this is one way of solving this.

However, I wonder if this was not better done automatically in [SshClient](https://github.com/apache/mina-sshd/blob/78ed6bc9/sshd-core/src/main/java/org/apache/sshd/client/SshClient.java#L755) by making sure the session's effective keypair provider does have a password finder set.

**Comment by ascertsimonm** [comment]
Heya

Yes, something like that but having things done automatically is better. Thanks

Simon

**Comment by abhishekpandey96** [comment]
Hi I am trying to add a passphrase with a dsa private key path  but I am getting org.apache.sshd.common.SshException: No more authentication methods available
        at org.apache.sshd.common.future.AbstractSshFuture.verifyResult(AbstractSshFuture.java:141)
        at org.apache.sshd.client.future.DefaultAuthFuture.verify(DefaultAuthFuture.java:56)
        at org.apache.sshd.client.future.DefaultAuthFuture.verify(DefaultAuthFuture.java:35)
        at org.apache.sshd.common.future.VerifiableFuture.verify(VerifiableFuture.java:45)


snipped code is :-
KeyIdentityProvider keyIdentityProvider = new KeyIdentityProvider() {
                    private final FileKeyPairProvider keyPairProvider = new FileKeyPairProvider(Paths.get(privateKeyPath));

                    @Override
                    public Iterable<KeyPair> loadKeys(SessionContext sessionContext) throws IOException {
                        return keyPairProvider.loadKeys(sessionContext);
                    }
                };

                client.setKeyIdentityProvider(keyIdentityProvider);

                try (ClientSession appSession = client.connect(appUserName, appHostName, appPort).verify(10000).getSession()) {
                    appSession.addPasswordIdentity(passphrase);
                    appSession.auth().verify();
