### ISSUE TITLE
Server side heartbeat not working

### ISSUE THREAD

**Issue by thevipwan** [apache/mina-sshd#298]
### Version

master

### Bug description

dependency：
```
<dependency>
    <groupId>org.apache.sshd</groupId>
    <artifactId>sshd-core</artifactId>
    <version>2.7.0</version>
</dependency>
```
Code：
```
SshServer sshd = SshServer.setUpDefaultServer();
sshd.setPort(3333);
sshd.setShellFactory(InteractiveProcessShellFactory.INSTANCE);
sshd.setSessionHeartbeat(SessionHeartbeatController.HeartbeatType.IGNORE, Duration.ofSeconds(5));
sshd.setKeyPairProvider(new ClassLoadableResourceKeyPairProvider(getClass().getClassLoader(), "rsa.key"));
sshd.setPasswordAuthenticator((username, password, session) -> username.equals(password));
sshd.start();
log.info("SSHD server started");
```

ssh Client:
``` 
user/passwd = test

ssh test@127.0.0.1 -p3333 
```

### Actual behavior

read [Server Setup Manual](https://github.com/apache/mina-sshd/blob/master/docs/server-setup.md) last section

I with my SSHD has ServerSide heartbeat，But setSessionHeartbeat API didn't working, ssh session didn't get any  interval heartbeat

### Expected behavior

SSHD automatic send heartbeat message for  each ssh session

**Comment by tomaswolf** [comment]
Why did you expect any heartbeats to be sent when you set heartbeat type `NONE`?

Try `SessionHeartbeatController.HeartbeatType.IGNORE`.

**Comment by thevipwan** [comment]
> SessionHeartbeatController.HeartbeatType.IGNORE

Try this, but still can't get any heartbeats

**Comment by tomaswolf** [comment]
1. I see that you are using version 2.7.0. Please try with 2.9.2, or with the master version.
2. How do you verify whether the client gets heartbeat messages?

**Comment by thevipwan** [comment]
switch to version 2.9.2 but still not work；I use debug log and Wireshark(Capture port traffic) monitor heartbeat，I'm so confused about it, can you give me correct example code?

**Comment by tomaswolf** [comment]
Indeed; you're right. It looks like this never worked, and was not caught because there was no test for server-side heartbeats.
