### ISSUE TITLE
requestNewKeysExchange may cause KeyExchangeMessageHandler into dead lock,cpu 100%

### ISSUE THREAD

**Issue by zmrush** [apache/mina-sshd#302]
### Version

2.9.1

### Bug description

i observed in cases， the write packet thread is always running  and in the interval i saw "equestNewKeysExchange(ClientSessionImpl[root@/47.104.92.124:22]) Initiating key re-exchange
method:o.a.s.c.s.ClientSessionImpl(AbstractSession.java:2404) " in log 

### Actual behavior

after i saw log "equestNewKeysExchange(ClientSessionImpl[root@/47.104.92.124:22]) Initiating key re-exchange
method:o.a.s.c.s.ClientSessionImpl(AbstractSession.java:2404)",the write packet thread is soar to 100%,not stopped

### Expected behavior

i expect when the connection is closed the cpu is down,and the thread is stopped

### Relevant log output

```Shell
equestNewKeysExchange(ClientSessionImpl[root@/47.104.92.124:22]) Initiating key re-exchange
method:o.a.s.c.s.ClientSessionImpl(AbstractSession.java:2404)
```

**Comment by zmrush** [comment]
![4D6AACE5-968A-475E-909D-5AF7CB62853A](https://user-images.githubusercontent.com/17923600/209339710-d6aa50f8-2078-4c5f-84ba-ed77b744d1d4.png)
![Uploading 76694429-AB75-4229-A733-7A51F5776628.png…]()

**Comment by tomaswolf** [comment]
Not enough information. Please provide full jstack traces as text file. If you have some code that can reproduce the behavior reliably that would also be helpful.

With just the information given, I don't see how one could even begin to investigate.

**Comment by zmrush** [comment]
it happens occasionally,not always.i guess that  when we write packet, the thread is in requestNewKeysExchange,so kexDone not fulfilled and the thread goes into "block = kexFlushedFuture;" and unfortunately, the connection is done,so the kexDone never done, and it goes into infinite loop

**Comment by zmrush** [comment]
> Not enough information. Please provide full jstack traces as text file. If you have some code that can reproduce the behavior reliably that would also be helpful.
> 
> With just the information given, I don't see how one could even begin to investigate.

i cannot paste all the jstack traces,because it may explode some information about my company, but it goes into infinite loop.you can see below two images,it goes in the "for;;" not ends
![4D6AACE5-968A-475E-909D-5AF7CB62853A](https://user-images.githubusercontent.com/17923600/209419534-c5700a1b-7796-4324-9f43-e4014240816f.png)
![76694429-AB75-4229-A733-7A51F5776628](https://user-images.githubusercontent.com/17923600/209419537-e5b85570-9751-4822-815f-0a42045a098f.png)

**Comment by tomaswolf** [comment]
@zmrush can you give #308 a try? I think that should avoid this endless loop.

**Comment by quequan** [comment]
we have faced same problem : KeyExchangeMessageHandler.writeOrEnqueue is running forever ,cpu usage is 100% . can you release a new version and publish to repo?
