### ISSUE TITLE
How to disable the warning "Server at xxxx preseneted unverfied EC key"

### ISSUE THREAD

**Issue by cl728** [apache/mina-sshd#304]
### Version

2.7.0

### Bug description

every time when the program connects to the remote host using apache-mina-sshd will print the WARN log like "Server at xxx presented unverfied EC key", I wonder how to disable it?

### Actual behavior

every time when the program connects to the remote host using apache-mina-sshd will print the WARN log like "Server at xxx presented unverfied EC key"

### Expected behavior

No WARN log like "Server at xxx preseneted unverfied EC key" be printed.

**Comment by jiahui-qin** [comment]
hi, I noticed that sometimes it is "EC key" and sometimes it is "RSA key", I want to force the use of "RSA Key", what should I do?
thanks a lot!
