### ISSUE TITLE
Client startup sometimes take a long time

### ISSUE THREAD

**Issue by garyiscoding** [apache/mina-sshd#306]
### Version

2.9.2

### Bug description

Sometimes the client starts quickly and sometimes slowly. 

long startTime = System.currentTimeMillis();
client = SshClient.setUpDefaultClient();
client.start();
LOGGER.info(String.format("start client cost [%s] ms", System.currentTimeMillis() - startTime));

When it is slow, it takes about 90 seconds to start. What is the solution

### Actual behavior

start client cost [9783] ms

### Expected behavior

start client cost [200] ms

**Comment by tomaswolf** [comment]
9783ms is 9.783s, not 90s.

It is impossible to answer this question from the information given. Might be anything, like the JVM having to load classes first, or garbage collection skewing the timing, or a virus scanner interfering, or anything else.

**Comment by garyiscoding** [comment]
> 9783ms is 9.783s, not 90s.
> 
> It is impossible to answer this question from the information given. Might be anything, like the JVM having to load classes first, or garbage collection skewing the timing, or a virus scanner interfering, or anything else.

**Comment by garyiscoding** [comment]
> 9783ms is 9.783s, not 90s.
> 
> It is impossible to answer this question from the information given. Might be anything, like the JVM having to load classes first, or garbage collection skewing the timing, or a virus scanner interfering, or anything else.

We need to log in to different machines frequently to execute commands.
We used to create a new client, then a new session, and then execute the command.
After executing the command, we close the session and client.
As a result, the next client creation will take a long time, even 200 seconds.

Later we tried to keep the client open and create a new session when we needed to execute a command.
The situation of delay does not appear any more. Is the method I used before wrong？

**Comment by tomaswolf** [comment]
Keeping the client open is certainly faster, but re-creating clients is also possible. JGit does so, for instance, and we never got any complaints. To find out why recreating clients sometimes takes such a long time in your setting, you'd have to profile your application. Perhaps that gives some insights.

**Comment by lshuq** [comment]
Hello, we have encountered the same problem and used the same solution. Have you found the cause of the problem?
