### ISSUE TITLE
What will cause the failure to open the channel

### ISSUE THREAD

**Issue by garyiscoding** [apache/mina-sshd#310]
Hello, may I ask what will cause the failure to open the channel? Is this the exception caught in the log

org.apache.sshd.common.SshException: DefaultOpenFuture[ChannelExec[id=123, recipient=-1]-ClientSessionImpl[root@/10.155.109.229:22]]: Failed (SshChannelOpenException) to execute: open failed

**Comment by tomaswolf** [comment]
From looking at where this exception is created, it seems that it indicates a failure in TCP/IP port fowarding to connect to the requested external port.

**Comment by garyiscoding** [comment]
When the service is first deployed, there is no error. After running for a while, this error occurs

![image](https://user-images.githubusercontent.com/121858742/212841990-ea8ef337-0412-40a2-8207-9786481972bb.png)

**Comment by garyiscoding** [comment]
`            long openChannelTimeout = 500L;
            try (ChannelExec channel = session.createExecChannel(command);
                ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
                ByteArrayOutputStream errorStream = new ByteArrayOutputStream()) {
                channel.setOut(outputStream);
                channel.setErr(errorStream);
                channel.open().verify(openChannelTimeout);
                channel.waitFor(EnumSet.of(CLOSED), execTimeout);

                Integer exitCode = channel.getExitStatus();
                String outputStr = StringUtils.chomp(outputStream.toString());
                String errorStr = StringUtils.chomp(errorStream.toString());
            }`

**Comment by garyiscoding** [comment]
`            long openChannelTimeout = 500L;
            try (ChannelExec channel = session.createExecChannel(command);
                ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
                ByteArrayOutputStream errorStream = new ByteArrayOutputStream()) {
                channel.setOut(outputStream);
                channel.setErr(errorStream);
                channel.open().verify(openChannelTimeout);
                channel.waitFor(EnumSet.of(CLOSED), execTimeout);

                Integer exitCode = channel.getExitStatus();
                String outputStr = StringUtils.chomp(outputStream.toString());
                String errorStr = StringUtils.chomp(errorStream.toString());
            }`

**Comment by garyiscoding** [comment]
long openChannelTimeout = 500L;
            try (ChannelExec channel = session.createExecChannel(command);
                ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
                ByteArrayOutputStream errorStream = new ByteArrayOutputStream()) {
                channel.setOut(outputStream);
                channel.setErr(errorStream);
                channel.open().verify(openChannelTimeout);
                channel.waitFor(EnumSet.of(CLOSED), execTimeout);

                Integer exitCode = channel.getExitStatus();
                String outputStr = StringUtils.chomp(outputStream.toString());
                String errorStr = StringUtils.chomp(errorStream.toString());
            }
