### ISSUE TITLE
Support for more than one jump host

### ISSUE THREAD

**Issue by nightman68** [apache/mina-sshd#318]
### Description

I have a special server running to which the connection is only possible via 2 jump hosts and my configuration for SSH looks like this:

``` bash
Host jump1
  Hostname                    jump1.corp
  Port                        22
  User                        nightman
  LogLevel                    QUIET

Host jump2
  HostName                    jump2.dmz.corp
  Port                        22
  User                        nightman
  ProxyJump                   jump1
  LogLevel                    QUIET

Host host*.dmz.corp
  ProxyJump                   nightman@jump2:22
```

This is working well with the native SSH clients.

It would be nice when your great libary would support such a configuration as well!

 :-)

### Motivation

Enhancements would make the library better usable for jump hosts.

### Alternatives considered

There is no workaround I found so far.

**Comment by tomaswolf** [comment]
Looks like this a shortcoming/bug in [SshClient.java](https://github.com/apache/mina-sshd/blob/801edabdb7723e9f5bf03fd66c6e48a2d240bb9f/sshd-core/src/main/java/org/apache/sshd/client/SshClient.java#L545), `connect()` and `doConnect()`: it appears to parse only the ProxyJump in the top-level Host entry.

As a work-around, try
```
Host host*.dmz.corp
  ProxyJump nightman@jump2:22,nightman@jump1:22
```
That should work (if I read the code right), and also should work with openSSH.

**Comment by nightman68** [comment]
@tomaswolf thanks for the quick response! I tested the workaround and it's working with one edit: the order of the proxy must be changed:

``` bash
Host host*.dmz.corp
  ProxyJump nightman@jump1:22,nightman@jump2:22
```
The other settings like in the original post.

Tested with openSSH 1.0.2 k on RH 7 and 1.1.1 i in a git bash.

**Comment by tomaswolf** [comment]
> For the native SSH client the order must be like proposed by you :-(

So there's even a bug in that implementation in Apache MINA sshd. Really :-(.

**Comment by nightman68** [comment]
If it will help I can run tests with a fixed pre package.

**Comment by tomaswolf** [comment]
Thanks for the offer. I won't have any time for any coding in the next few weeks, but perhaps someone else takes this on. Otherwise I'll take look sometime in March.

**Comment by nightman68** [comment]
Any update?

**Comment by tomaswolf** [comment]
Nope; I didn't get around to this yet. But it's up for grabs; we do welcome PRs.
