### ISSUE TITLE
How to: create sshclient with a private key

### ISSUE THREAD

**Issue by matzrm** [apache/mina-sshd#321]
### Version

3.0.0 alpha

### Bug description

Please,

can you provide an example on how to connect a mina ssh client to a server through a private key authentication?

### Actual behavior

Can't create a client witth private key.

### Expected behavior

Also in the cli client, missing the option to load the private key.

**Comment by tomaswolf** [comment]
You can add a private key to the session, before authenticating. Or use a HostConfigEntry that specifies a key file.

The CLI program in sshd-cli is not a fully featured replacement for the openSSH client. But it's true that it doesn't have the "-i" command-line option.
