### ISSUE TITLE
How to add KeyExchangeFactories using sshd-core 2.8 version

### ISSUE THREAD

**Issue by AtulParti** [apache/mina-sshd#324]
### Version

sshd-core 2.8 version

### Bug description

We have security violation for the following algorithms.
diffie-hellman-group-exchange-sha1
diffie-hellman-group1-sha1
gss-gex-sha1-*
gss-group1-sha1-*
gss-group14-sha1-*
rsa1024-sha1

We want to programatically to add the  specific alogorithm while starting the SSHServer. We tried many online samples like 

sshd.setKeyExchangeFactories(Arrays.asList(BuiltinKeyExchange.***));

BuiltinKeyExchange there is no class of the same name

List<KeyExchangeFactory> kexFactories = I need all the above mentioned deprecated kexAlgo, can you please help with the code snippet.

Kindly take this on priority.

### Actual behavior

Not able to set sshd.setKeyExchangeFactories(

### Expected behavior

Share the sample code how to set the KEX algos/

**Comment by AtulParti** [comment]
Can you please priorities as this is blocking us.

**Comment by AtulParti** [comment]
Can you help us to escalate this issue. This is a security violation and we are looking for an urgent help.

**Comment by tomaswolf** [comment]
No "security violation" here. Cut the alarmism.

Take a look at `BuiltInDHFactories` and `ClientBuilder.DH2KEX` or `ServerBuilder.DH2KEX`. I don't think there is any implementation of rsa1024-sha1.
