### ISSUE TITLE
[BUG]The command "source ~/.bashrc" is invalid.

### ISSUE THREAD

**Issue by jieguangzhou** [apache/mina-sshd#333]
### Version

2.9.0

### Bug description

When I execute the command "source ~.bashrc", it doesn't take effect. As shown below, there is an environment variable "ABC" in my bashrc, but I can't output it.k

The code is as follows:
```java
        ClientSession session = client.connect(user, host, port).verify().getSession();
        boolean result = session.auth().verify().isSuccess();
        if (result) {
            System.out.println("Success");
        } else {
            System.out.println("Failed");
        }
        System.out.println(result);

        String command = "cat ~/.bashrc && source ~/.bashrc && echo $ABC && echo END";
        String cmd = String.format(command);
        System.out.println(cmd);
        String executeResult = session.executeRemoteCommand(cmd);
        System.out.println(executeResult);
        client.stop();
```

### Actual behavior

The outputs is as follows:
```
.... some other contents.....
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export ABC=abc

END

```

### Expected behavior

I think the output should be 

```
.... some other contents.....
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export ABC=abc
abc
END

```

**Comment by jieguangzhou** [comment]
I'm not sure if I'm using it incorrectly, but what I actually expect is that it can read bashrc and other files by default, just like the behavior of directly executing them when I log in. Can anyone help me with this? Thank you very much.

**Comment by tomaswolf** [comment]
Apparently the command gets passed to the server all right. So you'd have to check what the server does. If that is not an Apache MINA sshd server, then it's not an Apache MINA sshd problem.

**Comment by jieguangzhou** [comment]
Thanks

> Apparently the command gets passed to the server all right. So you'd have to check what the server does. If that is not an Apache MINA sshd server, then it's not an Apache MINA sshd problem.

Thanks
