### ISSUE TITLE
direct-tcpip

### ISSUE THREAD

**Issue by cwww3** [apache/mina-sshd#335]
### Description

i start a sshd and type ssh(openssh) -L ... ,but i didn't receive "direct-tcpip" from client.

### Motivation

I want to know how ssh(openssl) implement local port forward.

**Comment by tomaswolf** [comment]
This is the issue tracker about Apache MINA sshd, a Java implementation of client and server-side SSH. It is not about openSSH. If you want to know how it's implemented in openSSH, ask the openSSH developers, or read [the code](https://github.com/openssh/openssh-portable).
