### ISSUE TITLE
Exception when try to ssh connect to ssh server

### ISSUE THREAD

**Issue by thachlp** [apache/mina-sshd#348]
### Version

2.9.2

### Bug description

I try to create a simple SSH Server
```
sshServer.setCommandFactory(new ProcessShellCommandFactory());
sshServer.setShellFactory(new ProcessShellFactory("/bin/sh", "-i", "-l"));
```
But when I try to connect to server by
```
ssh localhost -p <port> -o UserKnownHostsFile=/dev/null 
```
I received a exception:
```
exceptionCaught(ServerSessionImpl[thachle@/[0:0:0:0:0:0:0:1]:52686])[state=Opened] IOException: Cannot run program "-i": error=2, No such file or directory
```

### Actual behavior

Connection from client was closed:
```
Connection to localhost closed by remote host.
Connection to localhost closed.
```

### Expected behavior

We can access to SSH server with no error

**Comment by tomaswolf** [comment]
The documentation does not conform to the implementation. (Or vice versa.)

I don't understand the implementation of ProcessShellFactory. It appears that it expects a full command-line string in the first argument, and that argument broken down into the remaining arguments. So a call like `new ProcessShellFactory("/bin/sh -i -l", "/bin/sh", "-i", "-l")` _should_ work.

If you want to improve this to the first argument being the command and the remaining arguments the command arguments, feel free to provide a PR.

**Comment by thachlp** [comment]
Thanks for explaining it to me, I even don't know how to use it.
I will close the issue, let me try if I can improve it.
