### ISSUE TITLE
Does Apache Mina support MaxStartups feature of Standard SSHD

### ISSUE THREAD

**Issue by dbhakar** [apache/mina-sshd#350]
### Description

In SSHD there is parameter MaxStartups 10:30:60 which terminate unathorized connection once its reached 60. does Apache Mina SSHD support similiar type of functionality in Apache Mina SSHD 2.9.2?

### Motivation

it will solve DOS attack if any aunthorized user is trying to make connection then it can terminate once limit reached to 60.

### Alternatives considered

No as such

**Comment by tomaswolf** [comment]
It's not implemented in Apache MINA sshd, but I suppose it should be possible to implement this via a `SessionListener`. The basic idea (I didn't try this, though) would be to remember sessions in `sessionEstablished` or `sessionCreated`, and remove them in `sessionEvent` when the event is `Event.Authenticated`, and in `sessionClosed`. If the count is too high in `sessionCreated`, throw an exception.
