### ISSUE TITLE
Provide Snapshot builds of current master

### ISSUE THREAD

**Issue by HannesWell** [apache/mina-sshd#356]
### Description

Please publish snapshot builds of the current master.

The artifacts produced by the Github workflows on a push to the master could just be deployed to https://repository.apache.org/content/repositories/snapshots. 

The [apache 23 parent pom](https://repo1.maven.org/maven2/org/apache/apache/23/apache-23.pom) already has the `apache.snapshots.https` `snapshotRepository` defined.

Therefore, as described in the [GitHub documentation about publishing-java-packages-with-maven](https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository),
only another deploy job would have to be added that deploys the artifacts created by the first compile job.

I could provide a PR to implement that. The only thing you would have to do is to store the credentials for the apache snapshots repository in this repositories secret store and tell me the variable names so that it can be refered to when setting up the `server-username` and `server-password`.

### Motivation

Providing Snapshot builds of the current master-branch allows early testing and feedback of new changes.

**Comment by tomaswolf** [comment]
Good idea. I haven't found any proper documentation, but reading through a number of support tickets at the ASF it looks as if such credentials already exist.

I have opened https://issues.apache.org/jira/browse/INFRA-24609 to get some help. Not that we run off in the wrong direction :-)

Of course snapshots should only be published if the compile/test workflows succeeded. Also not on PRs.

Would we have to be careful about multiple builds on master running concurrently and then trying to deploy concurrently?

**Comment by HannesWell** [comment]
> I have opened https://issues.apache.org/jira/browse/INFRA-24609 to get some help. Not that we run off in the wrong direction :-)

Great, thanks.

> Of course snapshots should only be published if the compile/test workflows succeeded, and only if it's indeed a -SNAPSHOT version. Also not on PRs.

Yes, definitivly but that can be managed by using corresponding event filters.

> Would we have to be careful about multiple builds on master running concurrently and then trying to deploy concurrently?

We can just abort concurrently running deploy builds using
https://docs.github.com/en/actions/using-jobs/using-concurrency

To reduce the risik of partial deployments we can use deployAtEnd of the maven-deploy-plugin.

**Comment by tomaswolf** [comment]
The two secrets are named NEXUS_USER and NEXUS_PW. They have been enabled now for this repository.

Apparently that is all we need, so we can go forward with this.

**Comment by HannesWell** [comment]
> Apparently that is all we need, so we can go forward with this.

Great. 👍🏽
I'm on vacation for the next two weeks and therefore will not be able to help on this issue in that time.
Of course I can help with a PR when I'm back, unless you then already did it by yourself. :)

**Comment by tomaswolf** [comment]
Done. Here's what I came up with: [diff](https://github.com/apache/mina-sshd/compare/61c604c38deebe115fa3e8e209ea6f57cc506405...8b21743710d5593e3b193577f0be2feb15ad567f). I _hate_ yaml.

A first snapshot release is published already at the [Apache Snapshots](https://repository.apache.org/content/repositories/snapshots/) repo.

**Comment by HannesWell** [comment]
> Done. Here's what I came up with: [diff](https://github.com/apache/mina-sshd/compare/61c604c38deebe115fa3e8e209ea6f57cc506405...8b21743710d5593e3b193577f0be2feb15ad567f). I _hate_ yaml.
> 
> A first snapshot release is published already at the [Apache Snapshots](https://repository.apache.org/content/repositories/snapshots/) repo.

Great. Thank you!
Yaml isn't my favorit scripting language either.
