### ISSUE TITLE
Non Root User Apache Mina SSHD

### ISSUE THREAD

**Issue by dbhakar** [apache/mina-sshd#357]
### Description

I am implementing SFTP server using Apache Mina with NonRootUser so there can be N number of SFTP User which have individual directory each. when I am doing sftp for particular user its not checking Directory permission for SFTP user. its checking for Current user of OS.  

Example:
dbuser     SSHServer

/var/firstSftpUser
/var/SecondSftpUser

when connecting using firstUser then its should check whether firstUser have permission of /var/firstSftpUser or not then i want to write file with firstUser  istead of dbuser.

### Motivation

want to achieve sftp functinality similar to openssh

**Comment by tomaswolf** [comment]
I am not aware of any Java APIs that would support such functionality.
