### ISSUE TITLE
queries related to Apache MINA

### ISSUE THREAD

**Issue by akrattan** [apache/mina-sshd#363]
### Description

1.	SFTP ASCII transfer mode is supported in Apache MINA ?
2.	What are the SSH File Transfer Protocol versions supported in Apache MINA. 

### Motivation

1.	SFTP ASCII transfer mode is supported in Apache MINA ?
2.	What are the SSH File Transfer Protocol versions supported in Apache MINA.

**Comment by tomaswolf** [comment]
1. No. It also exists only since SFTP v4 (SSH_FXF_TEXT_MODE attribute). See also https://stackoverflow.com/a/33504576 .
2. See https://github.com/apache/mina-sshd/blob/master/docs/sftp.md#version-selection-via-sftpversionselector .

**Comment by techmaddy** [comment]
Is there any plan to support SFTP 4 ASCII transfer?
