### ISSUE TITLE
Exception occurred while transferring zip file from Linux system to Win10

### ISSUE THREAD

**Issue by 916004811** [apache/mina-sshd#369]
The exception caught is:
org.apache.sshd.sftp.common.SftpException: Failure
org.apache.sshd.sftp.client.impl.AbstractSftpClient.throwStatusException(AbstractSftpClient.java:217)
org.apache.sshd.sftp.client.impl.AbstractSftpClient.checkHandleResponse(AbstractSftpClient.java:255)
org.apache.sshd.sftp.client.impl.AbstractSftpClient.checkHandle(AbstractSftpClient.java:232)
org.apache.sshd.sftp.client.impl.AbstractSftpClient.open(AbstractSftpClient.java:574)
org.apache.sshd.sftp.client.impl.SftpOutputStreamAsync.\u003cint\u003e(SftpOutputSteamAsync.java:62)

I first use sftpclient.write to create a file, and then open to pass in the file stream

Although an exception was caught, the file was also successfully transferred. I would like to know how to avoid the occurrence of an exception

**Comment by 916004811** [comment]
version 2.8.0 or 2.9.2

**Comment by tomaswolf** [comment]
Not enough information. In any case, the server replied with a failure response in the open() call.
