### ISSUE TITLE
jgit ssh

### ISSUE THREAD

**Issue by panghu-max** [apache/mina-sshd#373]
I am using JGIT+Apache sshd ssh as the GIT hosting service, and I am currently encountering an issue.
How can I obtain the requested warehouse address in PublicickeyAuthenticator.authenticate.ServerSession? Or is there another way to obtain the warehouse address during authentication? This way, I can easily load the warehouse key based on the address

**Comment by tomaswolf** [comment]
Sorry, I don't understand what you mean. What is a warehouse address? Can you give a concrete example of what you are trying to do?
