### ISSUE TITLE
SftpFileSystemProvider.newFileChannel() uses wrong default mode

### ISSUE THREAD

**Issue by tomaswolf** [apache/mina-sshd#383]
### Version

master

### Bug description

According to the contract of `FileSystemProvider.newFileChannel()` per its javadoc, the channel is opened read-only if no `OpenOption`s are passed.

`SftpFileSystemProvider` opens the channel in read-write mode in this case.

### Actual behavior

Channel is opened read-write, which fails if the remote file is read-only.

### Expected behavior

Channel is opened read-only if `SftpFileSystemProvider.newFileChannel(path)` is called without `OpenOption`s.

**Comment by hannibal218bc** [comment]
Hi,

thank you for taking care of this issue. Sorry for nickpicking, but the description "the channel is opened read-only if no OpenOptions are passed" is not correct.

[The contract](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/FileChannel.html#open-java.nio.file.Path-java.util.Set-java.nio.file.attribute.FileAttribute...-) actually is "If neither option (`WRITE` or `APPEND`, ed.) is contained in the array then the file is opened for reading".

**Comment by tomaswolf** [comment]
Yes, but I would not read this too literally. All the other options imply write access, don't they?

**Comment by hannibal218bc** [comment]
> Yes, but I would not read this too literally. All the other options imply write access, don't they?

I thought specs are meant to be taken literally ;-) but yes, I agree that e.g. `SYNC` probably isn't useful on a read-only file. However, I think with e.g. `CREATE` it is not that clear.

**Comment by tomaswolf** [comment]
No sure there's a use case for CREATE, READ. For now I think your change #372 is fine (setting READ if no options). We can change it later to "set READ if neither WRITE nor APPEND present", if needed, but then that should probably be done in other places as well.

Do you want to fix the failing tests? I prefer to have master working at any commit, so if you could amend your commit, that'd be great; then I could merge it.

**Comment by hannibal218bc** [comment]
Sure, I've just force-pushed faf88ec0fd25c1907a75ffb415427ac7c9b7581c , could you please approve the action workflow run? :+1:
