### ISSUE TITLE
Add complete example for running an SSH server

### ISSUE THREAD

**Issue by caluml** [apache/mina-sshd#421]
### Version

2.10.0

### Bug description

I am trying to get the SSH server functionality running, and am having problems.

I think it might be useful for people new to the project and to the internals of SSH if there was a ready-made example of how to run an SSH server (with all the most common options).

The current documentation suggests using SshServer.setUpDefaultServer(), but even this needs HostKeyCertificateProviders, SignatureFactories etc specified, and I haven't been able to work out what I need to configure in order to get rid of "getKexProposal() no resolved signatures available."

It would be great if the example only included Java, without the need for files (keys, certs, etc) on the local filesystem.

### Actual behavior

There is no ready-made example that "just works"

### Expected behavior

A ready-made example that "just works".

**Comment by tomaswolf** [comment]
A server example _does_ exist at [SshServerMain](https://github.com/apache/mina-sshd/blob/master/sshd-cli/src/main/java/org/apache/sshd/cli/server/SshServerMain.java). Note that it is insecure: it allows any password log-in where the password equals the user name given, and it accepts any public key.

If you want it even simpler: here's a quick'n'dirty hack I sometimes use for testing:
```
import java.nio.file.Paths;
import java.time.Duration;

import org.apache.sshd.common.session.SessionHeartbeatController;
import org.apache.sshd.server.SshServer;
import org.apache.sshd.server.forward.AcceptAllForwardingFilter;
import org.apache.sshd.server.keyprovider.SimpleGeneratorHostKeyProvider;
import org.apache.sshd.server.shell.InteractiveProcessShellFactory;

public class TestServer {

    public static void main(String[] args) throws Exception {
        SshServer sshd = SshServer.setUpDefaultServer();
        sshd.setPort(12133);
        SimpleGeneratorHostKeyProvider hostKeys = new SimpleGeneratorHostKeyProvider(Paths.get("/tmp/a.ser"));
        sshd.setShellFactory(InteractiveProcessShellFactory.INSTANCE);
        sshd.setSessionHeartbeat(SessionHeartbeatController.HeartbeatType.IGNORE, Duration.ofSeconds(5));
        sshd.setKeyPairProvider(hostKeys);
        hostKeys.loadKeys(null);
        sshd.setPasswordAuthenticator((username, password, session) -> true);
        sshd.setPublickeyAuthenticator((username, pubkey, session) -> true);
        sshd.setForwardingFilter(AcceptAllForwardingFilter.INSTANCE);
        sshd.start();
        Thread.sleep(10000000);
    }
}
```
Listens on port 12133 and allows any password or public key.

**Comment by hth2** [comment]
Thanks for providing this example, as a beginner I find it very helpful! Very much appreciated.

Can you please give a hint how to use an existing key pair (generated by `ssh-gen`)?
