### ISSUE TITLE
mina-sftp : support for recursive copy with put

### ISSUE THREAD

**Issue by MOubari0** [apache/mina-sshd#423]
Hello, 

In order to copy recursively a directory (containing files) to a destination, the sftp's put command provide the -r option. But I'm not able to do that when communicating with a sftp server  that I coded using mina-sshd.

The class sshd.sftp.server.AbstractSftpSubsystemHelper throws a NoSuchFileException when resolving file attributes -> (Attribute N/A for target)

The solution that I found is to create the directory structure manually, so it seems that the server expects the destination directory to already exist.

Is there any solution I can implement on the server-side (maybe I'm missing something...)? or is it just not supported yet ?  

Thank you

**Comment by tomaswolf** [comment]
A recursive put needs to be implemented in the client. The SFTP draft RFCs do not mention anything about automatically creating missing directories. So the client has to create the directory structure top-down.
