### ISSUE TITLE
Ciphers and KEX override at ClientSession level not taken into account

### ISSUE THREAD

**Issue by baiglin** [apache/mina-sshd#439]
### Version

2.11.0

### Bug description

Hello, 

In our application we are connecting to multiple different sftp servers, that may require different configuration (ciphers, macs etc...) so I have created one SshClient with global settings

```java
  SshClient client = SshClient.setUpDefaultClient();
  // Option to delay kex init
  PropertyResolverUtils.updateProperty(client, CoreModuleProperties.SEND_IMMEDIATE_KEXINIT.getName(), false);
  client.setCipherFactoriesNameList("aes128-ctr,aes128-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc");
```

Then I create a new client session for each of my endpoint:

```java
  protected final ClientSession initClientSession() throws IOException {
    Duration verifyTimeout =
        sshdConfiguration.getTimeout() > 0 ? Duration.ofMillis(sshdConfiguration.getTimeout()) : null;

       // Open connection
      ClientSession clientSession =
        this.sshClient
            .connect(sshdConfiguration.getUserName(), sshdConfiguration.getHost(),
                sshdConfiguration.getPort())
            .verify(verifyTimeout)
            .getSession();

      // Override settings
      clientSession.setKeyExchangeFactories(createKeyExchanges(sshdConfiguration.getKex()));
      clientSession.setCipherFactoriesNameList(sshdConfiguration.getCipherList());
      clientSession.setMacFactoriesNameList(sshdConfiguration.getMacList());

      // Authentication setup
      setupAuthentication(clientSession);

      // Perform authentication
      clientSession.auth().verify(verifyTimeout);
   }

  private static List<KeyExchangeFactory> createKeyExchanges(String kexs) {
    BuiltinDHFactories.ParseResult result = BuiltinDHFactories.parseDHFactoriesList(kexs);
    return NamedFactory.setUpTransformedFactories(true, result.getParsedFactories(), ClientBuilder.DH2KEX);
  }

```

As you can see I have used the CoreModuleProperties.SEND_IMMEDIATE_KEXINIT property to delay the KEX init, as explained here https://github.com/apache/mina-sshd/blob/master/docs/client-setup.md#configuring-the-protocol-exchange-phase,
 however in my unit tests (I have setup apache mina server to act as a real server) I have random failures when I actually modify the list of ciphers to restrict the list, or the kex list. Sometimes the override is not used for the negotiation and instead client sends the ones setup at SshClient level, not at ClientSession level.

In debug mode, I could see that the kex init is delayed to protected AbstractClientSession#readIdentification(Buffer buffer)  method, however sometimes, it seems my override is not taken into account.

So I want to know if the way I am doing is valid or not, and if there is a way to avoid this concurrency issue....

Solutions could be to:
- Do the override on the sshClient, but as it is global, this means I may have concurrency issue on my side, as I transfer files in parallel, and I may initialize different client sessions in parallel. 
- Create different sshClient, but we saw that it creates internally thread pools and consumes a  lot of threads if I create too many clients
- Start/stop the sshclient if I create different sshClient, but I do not know how costly it is to do so. In the README, it is mentioned that we should share the client and stop it on application exit.

### Actual behavior

Randomly not taken into account the override of configuration done at ClientSession level

### Expected behavior

To be able to override ciphers, macs and Kex at Client Session level and not only globally at SshClient level

**Comment by tomaswolf** [comment]
I don't understand your example code. What's `client`? Seems undefined.

In any case: SEND_IMMEDIATE_KEXINIT = false delays sending the client's KEX init message until after the server's KEX init message has been received. But KEX init occur early in `connect()`, so re-configuring this afterwards does indeed result in a race condition.

Per-session configuration of the KEX proposal (ciphers, macs, and so on)  can be achieved for instance via `SessionListener.sessionNegotiationOptionsCreated`.

**Comment by tomaswolf** [comment]
The listener has access to the session, so it can do special things per session.

**Comment by baiglin** [comment]
Indeed, in my case I want to apply configuration on per-basis destination (user@IP:port), so I create many different client sessions and I would need to apply given configuration only on some client sessions, not the other, so my question is how can I distinguish sessions from the listener ?

So indeed I can do special things per session, my question is how can I distinguish the sessions.

**Comment by baiglin** [comment]
Indeed this is what I relied on after your last comment:

Implementing `SessionListener`

`  @Override
  public void sessionCreated(Session session) {
    InetSocketAddress remoteAddress = (InetSocketAddress)session.getIoSession().getRemoteAddress();
    if (remoteAddress.getHostName().equals(sshdConfiguration.getHost())
        && remoteAddress.getPort() == sshdConfiguration.getPort()) {
      setupCiphers(session);
      setupMacs(session);
      setupKeyExchanges(session);
    }
  }`
However at this stage of the exchange the user name was null in the exchange, so I cannot use it.

Many thanks @tomaswolf for your time.
