### ISSUE TITLE
When use the client, can't support the command: top 

### ISSUE THREAD

**Issue by heyefu19920626** [apache/mina-sshd#444]
### Version

2.11

### Bug description

when i use top command, the response is  'windows': unknown terminal type.
i run client on windows 10
![image](https://github.com/apache/mina-sshd/assets/25277783/ecc5cceb-5e0c-418c-9b3c-7b5baca3ea33)

### Actual behavior

![image](https://github.com/apache/mina-sshd/assets/25277783/96e15f44-1830-4f5e-9dae-f771ffc91397)

### Expected behavior

![image](https://github.com/apache/mina-sshd/assets/25277783/96e15f44-1830-4f5e-9dae-f771ffc91397)

**Comment by tomaswolf** [comment]
"Actual" and "expected" appear to be the same... but seriously: I think for "full screen terminal commands" like `top` your client would need to set appropriate Pty properties (type, columns, and rows, ...), and you might need to use some terminal emulator to get the control sequences be interpreted correctly.
