### ISSUE TITLE
How can I set the SftpFileSystem POOL_SIZE for my SshServer?

### ISSUE THREAD

**Issue by reckenrod** [apache/mina-sshd#448]
Hi. I am running a Mina-based Sftp server on v2.11.0. I am having performance issues compared to regular SSHD, so I want to try to tune the `POOL_SIZE` or other variables of the underlying `SftpFileSystem` to see if that helps as mentioned in the [2.11 release notes](https://github.com/apache/mina-sshd/releases/tag/sshd-2.11.0). I am not finding the `SftpModuleProperties` based way to set this intuitive however.

Here's some snippets of relevant code. I have a `MinaServerProvider` class creating an `SshServer`, and an `MinaSftpSubsystemFactory` where I create subsystems with SFTP hooks.

I'm just kindof floundering, trying to set the `POOL_SIZE` on objects which will allow me to here:
1. The `SshServer` I create and
2. the `ChannelSession` passed in the `createSubsystem` method.

Are either of these even the right objects to try to set this `POOL_SIZE` on? If not, what would be?

#### MinaServerProvider
```
class MinaServerProvider implements Provider<SshServer> {
....

    @Override
    public SshServer get() {
        log.info("Mina Log: Serving a Mina server");
        final SshServer server = SshServer.setUpDefaultServer();
        try {
            ....
            // set some server properties
            server.setSubsystemFactories(List.of(minaSftpSubsystemFactory));
            ....
            SftpModuleProperties.POOL_SIZE.set(server, 16);
            ....
            // start the server and return it
            ....
```

#### MinaSftpSubsystemFactory
```
class MinaSftpSubsystemFactory extends SftpSubsystemFactory {

    @Override
    public Command createSubsystem(ChannelSession channel) throws IOException {
        ....
        // set a hook
        ....
        SftpModuleProperties.POOL_SIZE.set(channel, 16);
        SftpSubsystem subsystem = new MinaSftpSubsystem(channel, this, minaSftpHook);
        return subsystem;
```

Thanks in advance :)

**Comment by tomaswolf** [comment]
Set it on the `SshServer` (for all SSH sessions) or on the `ServerSession`.

**Comment by reckenrod** [comment]
Thanks! This hasn't solved our performance issues; I'll open a new ticket for that if need be after further testing.
