### ISSUE TITLE
Looking for release date for next release of mina-sshd

### ISSUE THREAD

**Issue by adelel1** [apache/mina-sshd#487]
Hello,
We have recently moved to the latest LTS release of BC (due to a prev BC bug fix). However we have now been affected by this bug which is fixed now https://github.com/apache/mina-sshd/issues/455

I am wondering when you are able to do a new release incorporating the above. Is a 2.12 patch release possible, if 2.13 is too far off. The only way round it is to specify a BC system property on the command line.

**Comment by adelel1** [comment]
Hello, any update on this, either a patch release for 2.12 or a 2.13 release?

**Comment by tomaswolf** [comment]
Apache MINA sshd 2.13.1 is released and available in Maven Central.
