### ISSUE TITLE
Can I design a ssh server with sshd?

### ISSUE THREAD

**Issue by ZhouMM92** [apache/mina-sshd#496]
Now,I want to design a ssh server which can be connected by XShell or MobalXterm. And when I use XShell connect to this server, the server will verify the username and password from the XShell, when username and password is correct, then the connection can be created. After connected, the ssh server can output text to the Xshell, and also can receive input from the XShell.

So, can I implement this requirement with mina-sshd?

**Comment by tomaswolf** [comment]
Compared to e.g. an OpenSSH server you will lack certain functionalities like privilege separation or integration with the OS user management (PAM or whatever on Linux).

For general shell-level access I would not use Apache MINA SSHD.

But there are valid use cases for using Apache MINA SSHD to provide an SSH server component in an application. For instance, Gerrit uses it for git access over SSH, and for providing a restricted set of maintenance commands over SSH.

**Comment by ZhouMM92** [comment]
> Compared to e.g. an OpenSSH server you will lack certain functionalities like privilege separation or integration with the OS user management (PAM or whatever on Linux).
> 
> For general shell-level access I would not use Apache MINA SSHD.
> 
> But there are valid use cases for using Apache MINA SSHD to provide an SSH server component in an application. For instance, Gerrit uses it for git access over SSH, and for providing a restricted set of maintenance commands over SSH.

Thank you for the answer. But I indeed need to design a simple ssh server to interact with xshell . So, are there some simple examples that I can refer to？

**Comment by tomaswolf** [comment]
Look in [the documentation](https://github.com/apache/mina-sshd/blob/master/docs/server-setup.md) or in the tests.

**Comment by ZhouMM92** [comment]
> Look in [the documentation](https://github.com/apache/mina-sshd/blob/master/docs/server-setup.md) or in the tests.

Thank you very much. And I want to know which version is more stable and better that I can use.

**Comment by tomaswolf** [comment]
Use the latest.
