### ISSUE TITLE
how to  modifying the owner attribute of files and directories uploaded to the Linux system bye mina-sshd sftp-server

### ISSUE THREAD

**Issue by laonan007** [apache/mina-sshd#503]
### Description

how to  modifying the owner attribute of files and directories uploaded to the Linux system bye mina-sshd sftp-server.
The files and directory attributes uploaded now are all root

### Motivation

Can control the file owner attribute according to the uploaded user.

### Alternatives considered

none

### Additional context

none

**Comment by tomaswolf** [comment]
Apache MINA SSHD is a Java library and has no integration with the Linux user management, and it does not have privilege separation either.
