### ISSUE TITLE
Hello, does sshd now support http proxy connections?

### ISSUE THREAD

**Issue by yangzf01** [apache/mina-sshd#526]
### Description

How do I link ssh using a http proxy, is there an example or is there another solution?

### Motivation

We need to monitor some servers, but the network can't connect directly, we need to use a http proxy.

### Additional context

I read some of the issue, but there seems to be no follow up
like：
https://github.com/apache/mina-sshd/issues/309

**Comment by tomaswolf** [comment]
Other than what was mentioned at #309: no.
