### ISSUE TITLE
The sftp session fails to reuse the clientSession of the ssh session. Procedure

### ISSUE THREAD

**Issue by czldb2** [apache/mina-sshd#529]
![image](https://github.com/user-attachments/assets/58ac7ec3-4fce-4c22-adb1-2e37641a1b0a)
![image](https://github.com/user-attachments/assets/1bf4da2e-41d4-4682-82a8-d2052c0efb58)

### version
1.7.0
### phenomenon
I configured the ControlMaster for the ssh client, then implemented an ssh server using the mina-sshd component, first I cached the ClientSession created by the ssh session, and then reused the session when the sftp connection request came. I created fileSystem to handle sftp requests, but I ran into the problem shown above when uploading files

### question
Are there any changes related to the reuse of this ssh Clientsession to sftp sessions in the mina-sshd version? Or is there any restriction in 1.7.0?

**Comment by tomaswolf** [comment]
Don't know. Version 1.7.0 is very old. I don't understand what you are asking, and I don't understand why you mention ClientSession when you're implementing a server. Maybe search for old issues, either here on Github or in the ASF JIRA.

**Comment by czldb2** [comment]
> Don't know. Version 1.7.0 is very old. I don't understand what you are asking, and I don't understand why you mention ClientSession when you're implementing a server. Maybe search for old issues, either here on Github or in the ASF JIRA.

Thank you very much for your reply. I have rewritten the sample code of 1.7.0 and 2.13.0. In fact, it is feasible, maybe it is caused by my other code interference
