### ISSUE TITLE
SftpSubSystem processes sftp request data 1-2 times slower than openSSH

### ISSUE THREAD

**Issue by czldb2** [apache/mina-sshd#584]
### Version
2.13.2

### problem
Why doesn't SftpSubSystem aggregate the data for handling sftp packets like SftpOutputStreamAsync's internalTransfer() method? Otherwise, under certain network delay and bandwidth limitation, SftpSubSystem will be much slower than openSSH to handle uploading and downloading and ls file listing commands.

**Comment by LiQingFeng7** [comment]
I would like to ask you how to improve the data processing speed of SftpSubsystem to the same level as openSSH? Do we have any configurations that can support such a boost?

**Comment by tomaswolf** [comment]
This is too unspecific.

Probably there are optimization possibilities on the server side. Feel free to investigate and propose a PR to improve the speed.

**Comment by tomaswolf** [comment]
Besides, I see you specified 2.13.2. Do try 2.14.0-SNAPSHOT. The cipher improvements we did are generally effective.

**Comment by LiQingFeng7** [comment]
### precondition
This is one of my sample code：
[sshtest.zip](https://github.com/user-attachments/files/16671055/sshtest.zip)

This is my sftp server configuration and I added a custom fileSystem and FileSubSystem
![17241400592348](https://github.com/user-attachments/assets/3cb24edc-23fd-4d7b-9958-edd9d530354b)

I overwrote the CreateFileSystem() method of the custom SftpFileSystemFactory so that I could use this sftp server to connect to other linux machines and connect their file systems
![17241401646827](https://github.com/user-attachments/assets/b4ef8d5f-2b92-4656-9033-7095163a4c60)
![17241403468425](https://github.com/user-attachments/assets/e59f23d9-a97c-414e-bf05-cde5986bff11)
![image](https://github.com/user-attachments/assets/1dbd0d02-a538-4032-a46f-208afa8dcbc0)

### phenomenon
When I use the sftp server to connect to the file system of the target machine, I use the put or ls command to upload files and view the files in the current directory.

Then I compared using sftpclient.write(), which is about 1-2 times slower
![image](https://github.com/user-attachments/assets/60b9dd1a-1a9c-4b3c-8d3d-932fad30a937)

Then I looked at the method time using the performance observation tool and found that the sftpSubSystem's doWrite() method did not aggregate sftp data for sending like the internalTransfer() method in the SftpOutputStreamAsync class.
![17240471215166](https://github.com/user-attachments/assets/4152768b-a0c8-407e-b438-4ea5db11536d)

### problem
Then I used version 2.14.0 natively and the effect was the same, which I assumed was due to the differences found above. I would like to ask is it possible for SftpSubSystem to implement the same processing as the SftpOutputStreamAsync class?

**Comment by tomaswolf** [comment]
So your server is like an SFTP proxy (it doesn't use the local file system, but connects again to some other server and forwards stuff). Basically you have

```
SFTP Client ---> SFTP Server A ---> SFTP Client  (on A) ---> SFTP server "targetIP"
```

I'm aware of the performance problems with this. SFTP is not well suited for such kind of proxying; you're probably better off forwarding SFTP requests directly. (Basically, don't use a filesystem but a special purpose SftpSubsystem that forwards requests directly, without ever going to the filesystem. The filesystem is just an awkward detour for such a use case.)

And no, the "same processing as in SftpOutputStreamAsync" won't help. The server A only sees a series of write requests; it doesn't know that these writes are contiguous or even in sequence.

I do wonder about your claim that it was "1-2 times slower than OpenSSH". How do you do this kind of SFTP proxying with OpenSSH on server A? It _is_ 1-2 times slower than uploading the file directly to the "targetIP" server, whether that targetIP server runs OpenSSH or Apache MINA sshd.

**Comment by LiQingFeng7** [comment]
> So your server is like an SFTP proxy (it doesn't use the local file system, but connects again to some other server and forwards stuff). Basically you have
> 
> ```
> SFTP Client ---> SFTP Server A ---> SFTP Client  (on A) ---> SFTP server "targetIP"
> ```
> 
> I'm aware of the performance problems with this. SFTP is not well suited for such kind of proxying; you're probably better off forwarding SFTP requests directly. (Basically, don't use a filesystem but a special purpose SftpSubsystem that forwards requests directly, without ever going to the filesystem. The filesystem is just an awkward detour for such a use case.)
> 
> And no, the "same processing as in SftpOutputStreamAsync" won't help. The server A only sees a series of write requests; it doesn't know that these writes are contiguous or even in sequence.
> 
> I do wonder about your claim that it was "1-2 times slower than OpenSSH". How do you do this kind of SFTP proxying with OpenSSH on server A? It _is_ 1-2 times slower than uploading the file directly to the "targetIP" server, whether that targetIP server runs OpenSSH or Apache MINA sshd.

Thank you very much for your quick reply. openSSH I directly use the sftp command to connect to the target machine and put the upload to check the speed. Then I overwrote the doWrite() method on SftpSubSystem and used JSCH to open a fd again for put operation, which was as fast as openSSH.

**Comment by LiQingFeng7** [comment]
> > openSSH I directly use the sftp command to connect to the target machine and put the upload to check the speed.
> 
> So you compare the speed of a direct connection to "targetIP" against an indirect connection via "A"?
> 
> > Then I overwrote the doWrite() method on SftpSubSystem and used JSCH to open a fd again for put operation, which was as fast as openSSH.
> 
> That's what I wrote above, forwarding requests without going to a filesystem at all. Should be possible to do with an Apache MINA sshd client, too. If done correctly, server A wouldn't even have its own file handles -- it'd forward everything to targetIP, and funnel back responses to the client.
> 
> In fact, just using an SSH tunnel going through A to "targetIP" is probably even simpler.



> > openSSH I directly use the sftp command to connect to the target machine and put the upload to check the speed.
> 
> So you compare the speed of a direct connection to "targetIP" against an indirect connection via "A"?
> 
> > Then I overwrote the doWrite() method on SftpSubSystem and used JSCH to open a fd again for put operation, which was as fast as openSSH.
> 
> That's what I wrote above, forwarding requests without going to a filesystem at all. Should be possible to do with an Apache MINA sshd client, too. If done correctly, server A wouldn't even have its own file handles -- it'd forward everything to targetIP, and funnel back responses to the client.
> 
> In fact, just using an SSH tunnel going through A to "targetIP" is probably even simpler.

Yes, because I compared rewriting the SftpSubSystem's dowrite() method using jsch in a way that was consistent with the speed of a direct openSSH connection to "targetIP", then removed the rewritten method for comparison and found that it was much slower.

**Comment by LiQingFeng7** [comment]
> I'm aware of the performance problems with this. SFTP is not well suited for such kind of proxying; you're probably better off forwarding SFTP requests directly. (Basically, don't use a filesystem but a special purpose SftpSubsystem that forwards requests directly, without ever going to the filesystem. The filesystem is just an awkward detour for such a use case.)
If I want an interactive sftp terminal, is there only one way to create fileSystem? Also, can I ask you about the simple example you mentioned of using mina-sshd to forward sftp requests directly over SftpSubsystem?

**Comment by tomaswolf** [comment]
> If I want an interactive sftp terminal, is there only one way to create fileSystem?

I don't understand the question. You don't need a file system to write an SFTP Client.

> Also, can I ask you about the simple example you mentioned of using mina-sshd to forward sftp requests directly over SftpSubsystem?

There is no such example. You'd have to implement it yourself.

**Comment by LiQingFeng7** [comment]
> I don't understand the question. You don't need a file system to write an SFTP Client.

This is my misunderstanding, that is I can customize a SubSystem to handle sftp requests and forward them directly without having to create a file system for extra processing, which can avoid too much performance loss.

> There is no such example. You'd have to implement it yourself.

Yeah, I was just beginning to understand there was a problem. Thank you very much for your reply.
