### ISSUE TITLE
Migrated from sshd core and common libraries from 2.6x to 2.12.1 and notices bash history logging is enabled

### ISSUE THREAD

**Issue by satish-seshamani-imprivata** [apache/mina-sshd#588]
### Version

2.12.1

### Bug description

Recently migrated sshd-core,sshd-common, sshd-sftp and sshd-putty libraries from 2.6.0 to 2.12.1 . Since this update we started noticing scripts executed by the sshclient using org.apache.sshd.client.channel.ClientChannel logs all commands executed in the history logs. This is a security concern as some of our scripts includes updating user passwords which is now visible in plain text. We can disable this by first disabling history using "set +o history" or unset HISTFILE , but we did not have to do this with the 2.6x version. Is this a bug or is there a property we can set to disable history logging?

### Actual behavior

All commands executed via  org.apache.sshd.client.channel.ClientChannel  is logged in bash history 

### Expected behavior

history logging should be disabled for the clientsession

**Comment by tomaswolf** [comment]
The bash history is completely beyond whatever Apache MINA sshd does.

**Comment by satish-seshamani-imprivata** [comment]
ok, thanks for the update. strange that there was not logging with the 2.6x versions. In any case this ticket can be closed
