### ISSUE TITLE
How to add mac algorithm and cipher algorithm supported by BC library to mina-sshd?

### ISSUE THREAD

**Issue by LiQingFeng7** [apache/mina-sshd#594]
### version
1.7.0

### problem
If I want to add the BC library's already implemented algorithms to the mina-sshd server and client, how do I start?

**Comment by LiQingFeng7** [comment]
![image](https://github.com/user-attachments/assets/cb978511-5aa6-47b2-9369-f91a380d6fa8)
I added these two changes in the code of mina-sshd1.7.0. According to my current understanding of the mina-sshd code, if the BC library supports the corresponding implementation, I should be able to use the mac algorithm through Mina-sshd normally, right?

![image](https://github.com/user-attachments/assets/5ae88c55-2d5c-4008-96dd-15ea21ee80e1)
However, there are mac algorithm problems on the target asset side


I would like to ask, is there any other way to correctly add the algorithm supported by the BC library?

**Comment by tomaswolf** [comment]
There is no IETF standard (RFC) yet for using ShangMi in SSH.

Just adding the hash apparently isn't enough. Or you hit a bug in the SM3 implementation in either BC or in the peer. Or there is some other constraint.

Besides modifying the enum you could also try the extension mechanism via `BuiltinMacs.registerExtension()`.

Also; version 1.7.0 is very old. I'd suggest to move to 2.13.2.
