### ISSUE TITLE
use java module feature

### ISSUE THREAD

**Issue by ithander** [apache/mina-sshd#624]
### Description

[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.server
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.server.shell
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.session
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.session.helpers
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.kex
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.kex.extension
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.io
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.future
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.config
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.channel
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.auth
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.pubkey
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.password
[ERROR] 未命名的模块同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.hostbased
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.server
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.server.shell
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.session
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.session.helpers
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.kex
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.kex.extension
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.io
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.future
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.config
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.channel
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.auth
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.pubkey
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.password
[ERROR] 模块 org.apache.sshd.cli 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.hostbased
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.server
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.server.shell
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.session
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.session.helpers
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.kex
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.kex.extension
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.io
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.future
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.config
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.channel
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.auth
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.pubkey
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.password
[ERROR] 模块 org.apache.sshd.common 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.hostbased
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.server
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.server.shell
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.session
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.session.helpers
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.kex
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.kex.extension
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.io
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.future
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.config
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.channel
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.common.auth
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.pubkey
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.password
[ERROR] 模块 org.apache.sshd.core 同时从 org.apache.sshd.common 和 org.apache.sshd.core 读取程序包 org.apache.sshd.client.auth.hostbased
[ERROR] /C:/test_workspace/mana/src/main/java/module-info.java:[1,1] 模块 org.ithang.mana 同时从 org.apache.sshd.core 和 org.apache.sshd.common 读取程序包 org.apache.sshd.server

### Motivation

module org.ithang.mana {
    requires javafx.controls;
    requires javafx.fxml;
	requires javafx.graphics;
	requires javafx.base;
	requires javafx.web;
	requires jdk.jsobject;
	requires transitive org.apache.sshd.core;
	requires org.apache.sshd.common;
	requires org.apache.sshd.cli;
    opens org.ithang.mana to javafx.fxml;
    exports org.ithang.mana;
}

**Comment by tomaswolf** [comment]
If you want to use modules, do **not** use `org.apache.sshd.core` and `org.apache.sshd.common`; they have split packages.

Use `org.apache.sshd.osgi` instead.

**Comment by ithander** [comment]
Use org.apache.sshd.osgi instead. it is work
