### ISSUE TITLE
Can I have a separate resource limit for sftp?

### ISSUE THREAD

**Issue by LiQingFeng7** [apache/mina-sshd#640]
### problem description
I wrote an ssh server using mina-sshd, where sftp sessions often consumed unlimited system resources when there were many transfer tasks, which affected ssh sessions and other processes.

### questions
I would like to ask if mina-sshd is configured to limit the system resource usage of sftp function separately without affecting SSH-related functions?

**Comment by tomaswolf** [comment]
No. Sftp runs over an SSH channel. Sounds like you need to implement some rate limiting, such as allowing only a maximum number of sftp channels in a SSH session, or a maximum number of SSH sessions per client IP.

**Comment by LiQingFeng7** [comment]
> No. Sftp runs over an SSH channel. Sounds like you need to implement some rate limiting, such as allowing only a maximum number of sftp channels in a SSH session, or a maximum number of SSH sessions per client IP.

Thank you.
